Entrada y Salida en Celdas
-----

In [2]:
1+2

3

In [3]:
1+1
1+2

3

In [4]:
La función print
Nota: print es una función en Python 3. Es necesario usar parentesis. 


SyntaxError: invalid syntax (<ipython-input-4-8ea9cb0d3212>, line 1)

In [6]:
print(1+2)

3


Variables
=====

Hay muchos tipos de variables en Python 3. Los tipos más comunes son: 
    
Numéricos
----------
    
* bool
* int
* float
* complex
    

In [9]:
a = 4
b = 1.5
c = 121212121212121212121212121212121212121212121212121212121212121212121212
d = 1j
e = 1/3
f = True

In [10]:
a+b

5.5

In [11]:
a*c

484848484848484848484848484848484848484848484848484848484848484848484848

In [12]:
(b+d)*a

(6+4j)

In [13]:
a+f

5

In [14]:
type(1.5)

float

In [16]:
e


0.3333333333333333

Existen otros tipos de datos básicos, que veremos más adelante (list, tuple, dict)

Matemáticas en Python
------------

In [17]:
1+1

2

In [18]:
3-4

-1

In [19]:
14/5

2.8

In [20]:
14//5

2

In [21]:
2*5

10

In [22]:
2**3

8

In [23]:
10%3

1

Arreglos multidimensionales en Numpy
===================

El objeto `ndarray` es el objeto principal para representar arreglos de datos. Este objeto puede manejar arreglos multidimensionales de cualquier tamaño (restringido a la memoria del ordenador). 

* Un `ndarray` tiene un tamaño fijo. Para modificar su tamaño hay que crear un nuevo arreglo. 
* Un `ndarray` permite operaciones "elemento por elemento"

El objeto `ndarray` está definido en el módulo numpy

In [25]:
import numpy as np

In [36]:
a = np.arange(100)

In [37]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
b = np.arange(3,103)
b

array([  3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102])

In [40]:
c = np.arange(1,100,2)

In [ ]:
Sumar un número fijo a un arreglo

In [42]:
a + 7

array([  7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,
        20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
        33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
        46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
        59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 104, 105, 106])

In [49]:
a + b

array([  3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,
        29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,
        55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,
        81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105,
       107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131,
       133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157,
       159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183,
       185, 187, 189, 191, 193, 195, 197, 199, 201])

In [50]:
a * b

array([    0,     4,    10,    18,    28,    40,    54,    70,    88,
         108,   130,   154,   180,   208,   238,   270,   304,   340,
         378,   418,   460,   504,   550,   598,   648,   700,   754,
         810,   868,   928,   990,  1054,  1120,  1188,  1258,  1330,
        1404,  1480,  1558,  1638,  1720,  1804,  1890,  1978,  2068,
        2160,  2254,  2350,  2448,  2548,  2650,  2754,  2860,  2968,
        3078,  3190,  3304,  3420,  3538,  3658,  3780,  3904,  4030,
        4158,  4288,  4420,  4554,  4690,  4828,  4968,  5110,  5254,
        5400,  5548,  5698,  5850,  6004,  6160,  6318,  6478,  6640,
        6804,  6970,  7138,  7308,  7480,  7654,  7830,  8008,  8188,
        8370,  8554,  8740,  8928,  9118,  9310,  9504,  9700,  9898, 10098])

In [51]:
a.dot(b)

343200